"""add reference_id to booking

Revision ID: 12db214711c9
Revises: 9efc081197c2
Create Date: 2026-06-02 23:57:27.924324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12db214711c9'
down_revision = '9efc081197c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_reference_id'), ['reference_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_reference_id'))
        batch_op.drop_column('reference_id')

    # ### end Alembic commands ###
