"""add booking status enum

Revision ID: 2b2d4123e73e
Revises: 848e673ef07f
Create Date: 2026-05-31 20:59:13.195097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2d4123e73e'
down_revision = '848e673ef07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='bookingstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
