"""remove recived

Revision ID: 468d336d6b8a
Revises: 2b2d4123e73e
Create Date: 2026-05-31 21:28:21.839099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468d336d6b8a'
down_revision = '2b2d4123e73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('are_received')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('are_received', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
