"""add come from

Revision ID: 848e673ef07f
Revises: f8ca1017dbe3
Create Date: 2026-05-19 19:31:27.500210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848e673ef07f'
down_revision = 'f8ca1017dbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comes_from', sa.String(length=100), nullable=True))

    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comes_from', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.drop_column('comes_from')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('comes_from')

    # ### end Alembic commands ###
