"""unify status enum

Revision ID: 9efc081197c2
Revises: 468d336d6b8a
Create Date: 2026-05-31 22:28:20.610283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efc081197c2'
down_revision = '468d336d6b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True))
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('is_resolved')

    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True))
        batch_op.drop_column('is_reviewed')
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_reviewed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resolved', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
