"""add examination table

Revision ID: f8ca1017dbe3
Revises: 6f5eb9998528
Create Date: 2026-05-17 23:50:38.918106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ca1017dbe3'
down_revision = '6f5eb9998528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('symptom_text', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examinations')
    # ### end Alembic commands ###
